version: "3"

services:
  app:
    build: 
      context: .
    ports: 
      - "8000:8000"
    volumes: 
      - ./app:/app
      #to restart automatic without close docker then open it again
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"


